# frozen_string_literal: true

require 'pathname'
require_relative '../../../../lib/flexdot'

Flexdot.setup(
  dotfiles_dir: '.',
  home_dir: '..',
  output_colorize: false,
  keep_max_backup_count: 1
)
