
name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest

    # Run this build only on either pull request or push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        ruby_version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake test
